In [11]:
import math
import warnings

import numpy as np
import optuna
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBRegressor

warnings.filterwarnings('ignore')
sns.set_style("whitegrid")
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_parquet('../data/data_with_meteo_and_holidays.parquet')
df.head()

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune,temperature_2m,precipitation,rain,snowfall,relative_humidity_2m,is_holiday
0,16107,Benjamin Godard - Victor Hugo,OUI,35.0,30,5,2,3,OUI,OUI,2024-10-21 12:49:53+00:00,"[48.865983, 2.275725]",Paris,75056,20.75,0.0,0.0,0.0,71.68051,1
1,9020,Toudouze - Clauzel,OUI,21.0,18,2,0,2,OUI,OUI,2024-10-21 12:46:01+00:00,"[48.87929591733507, 2.3373600840568547]",Paris,75056,20.75,0.0,0.0,0.0,71.68051,1
2,14111,Cassini - Denfert-Rochereau,OUI,25.0,21,1,1,0,OUI,OUI,2024-10-21 12:47:41+00:00,"[48.837525839067, 2.3360354080796]",Paris,75056,20.75,0.0,0.0,0.0,71.68051,1
3,13007,Le Brun - Gobelins,OUI,48.0,40,4,1,3,OUI,OUI,2024-10-21 12:49:56+00:00,"[48.835092787824, 2.3534681351338]",Paris,75056,20.75,0.0,0.0,0.0,71.68051,1
4,5110,Lacépède - Monge,OUI,23.0,6,17,7,10,OUI,OUI,2024-10-21 12:48:48+00:00,"[48.84389286531899, 2.3519663885235786]",Paris,75056,20.75,0.0,0.0,0.0,71.68051,1

In [3]:
df['hour'] = df['duedate'].dt.hour
df['month'] = df['duedate'].dt.month
df['dayofweek'] = df['duedate'].dt.dayofweek
df['is_weekend'] = df['dayofweek'].apply(lambda x: 1 if x >= 5 else 0)

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['dow_sin'] = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos'] = np.cos(2 * np.pi * df['dayofweek'] / 7)

df

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune,temperature_2m,precipitation,rain,snowfall,relative_humidity_2m,is_holiday,hour,month,dayofweek,is_weekend,hour_sin,hour_cos,dow_sin,dow_cos
0,16107,Benjamin Godard - Victor Hugo,OUI,35.0,30,5,2,3,OUI,OUI,2024-10-21 12:49:53+00:00,"[48.865983, 2.275725]",Paris,75056,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
1,9020,Toudouze - Clauzel,OUI,21.0,18,2,0,2,OUI,OUI,2024-10-21 12:46:01+00:00,"[48.87929591733507, 2.3373600840568547]",Paris,75056,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
2,14111,Cassini - Denfert-Rochereau,OUI,25.0,21,1,1,0,OUI,OUI,2024-10-21 12:47:41+00:00,"[48.837525839067, 2.3360354080796]",Paris,75056,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
3,13007,Le Brun - Gobelins,OUI,48.0,40,4,1,3,OUI,OUI,2024-10-21 12:49:56+00:00,"[48.835092787824, 2.3534681351338]",Paris,75056,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
4,5110,Lacépède - Monge,OUI,23.0,6,17,7,10,OUI,OUI,2024-10-21 12:48:48+00:00,"[48.84389286531899, 2.3519663885235786]",Paris,75056,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179165,19018,Cité de la Musique,OUI,60.0,55,3,1,2,OUI,OUI,2025-12-15 07:29:33+00:00,"[48.888796556487, 2.3925811931922]",Paris,75056,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179166,18043,Clichy - Place Blanche,OUI,20.0,18,2,0,2,OUI,OUI,2025-12-15 07:23:42+00:00,"[48.883601088297, 2.3332237824798]",Paris,75056,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179167,8203,Matignon - Faubourg Saint-Honoré,OUI,35.0,10,24,11,13,OUI,OUI,2025-12-15 07:26:42+00:00,"[48.871499100264, 2.3138961727427]",Paris,75056,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179168,12105,Bercy - Villot,OUI,33.0,0,38,28,10,OUI,OUI,2025-12-15 07:29:25+00:00,"[48.841795009027, 2.3767850184816]",Paris,75056,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179169,15056,Place Balard,OUI,22.0,0,36,27,9,OUI,OUI,2025-12-15 07:29:28+00:00,"[48.836395736424, 2.2784192115068]",Paris,75056,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0

In [4]:
targets = ['numbikesavailable', 'numdocksavailable']
to_drops = ['duedate', 'nom_arrondissement_communes','is_returning',
            'coordonnees_geo', 'is_renting', 'is_installed', 'code_insee_commune', 'mechanical', 'ebike']

ref_date = '2025-12-20 00:00:00+00:00'

df_train = df[df['duedate'] < ref_date]
df_test = df[df['duedate'] > ref_date]

X_train = df_train.drop(columns=targets + to_drops)
X_test = df_test.drop(columns=targets + to_drops)
y_train = df_train[targets]
y_test = df_test[targets]

print(f"(X_train.shape, y_train.shape, X_test.shape, y_test.shape) = {(X_train.shape, y_train.shape, X_test.shape, y_test.shape)}")
X_train

(X_train.shape, y_train.shape, X_test.shape, y_test.shape) = ((115597, 17), (115597, 2), (63573, 17), (63573, 2))

,stationcode,name,capacity,temperature_2m,precipitation,rain,snowfall,relative_humidity_2m,is_holiday,hour,month,dayofweek,is_weekend,hour_sin,hour_cos,dow_sin,dow_cos
0,16107,Benjamin Godard - Victor Hugo,35.0,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
1,9020,Toudouze - Clauzel,21.0,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
2,14111,Cassini - Denfert-Rochereau,25.0,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
3,13007,Le Brun - Gobelins,48.0,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
4,5110,Lacépède - Monge,23.0,20.75,0.0,0.0,0.0,71.680510,1,12,10,0,0,1.224647e-16,-1.000000,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179165,19018,Cité de la Musique,60.0,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179166,18043,Clichy - Place Blanche,20.0,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179167,8203,Matignon - Faubourg Saint-Honoré,35.0,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179168,12105,Bercy - Villot,33.0,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0
179169,15056,Place Balard,22.0,4.85,0.0,0.0,0.0,93.897484,0,7,12,0,0,9.659258e-01,-0.258819,0.0,1.0

In [5]:
categorical_features = X_train.select_dtypes(include=["object", "category"]).columns
categorical_features

Index(['stationcode', 'name'], dtype='object')

In [6]:
numeric_features = X_train.select_dtypes(exclude=['object']).columns

def create_preprocessor(num_features, cat_features):
    numeric_transformer = Pipeline(
        steps=[
            ('scaler', StandardScaler()),
            ("imputer", SimpleImputer(strategy="median"))
        ]
    )

    categorical_transformer = Pipeline(
        steps=[
            ("encoder", OneHotEncoder(handle_unknown="ignore")),
            ("imputer", SimpleImputer(strategy="most_frequent"))
        ]
    )

    pipeline = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_features),
            ("cat", categorical_transformer, cat_features),
        ]
    )

    return pipeline

In [7]:
preprocessor = create_preprocessor(numeric_features, categorical_features)

def objective(trial):
    hyper_params = {
        "n_estimators": trial.suggest_int("n_estimators", 600, 800),
        "max_depth": trial.suggest_int("max_depth", 7, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.2, 0.3, log=True),
        "min_child_weight": trial.suggest_int("min_child_weight", 5, 9),
        "reg_lambda": trial.suggest_float("reg_lambda", 1, 20, log=True),
        "reg_alpha": trial.suggest_float("reg_alpha", 40, 70),
        "subsample": trial.suggest_float("subsample", 0.5, 0.8),
        "gamma": trial.suggest_float("gamma", 7, 9),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.8, 1.0),
        "random_state": 42,
        "n_jobs": -1
    }

    model = XGBRegressor(**hyper_params, device='gpu')

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('model', model)
        ]
    )

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    return r2_score(y_test, y_pred)

In [8]:
study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(),
                            pruner=optuna.pruners.MedianPruner())
study.optimize(objective, n_trials=50, n_jobs=1)

best_params = study.best_params
best_params

[I 2026-01-05 09:37:26,470] A new study created in memory with name: no-name-605219b1-d499-44b2-a13e-0a85496e1464
[I 2026-01-05 09:37:37,852] Trial 0 finished with value: 0.5615689158439636 and parameters: {'n_estimators': 725, 'max_depth': 9, 'learning_rate': 0.2724197689068724, 'min_child_weight': 5, 'reg_lambda': 2.0497429377335865, 'reg_alpha': 45.13312578809162, 'subsample': 0.5478316881342762, 'gamma': 7.387696020253665, 'colsample_bytree': 0.9721139061702043}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:37:51,081] Trial 1 finished with value: 0.5393623113632202 and parameters: {'n_estimators': 696, 'max_depth': 7, 'learning_rate': 0.24746430086689486, 'min_child_weight': 9, 'reg_lambda': 4.151327962278146, 'reg_alpha': 55.36342627355281, 'subsample': 0.5099373232024689, 'gamma': 8.802874112816344, 'colsample_bytree': 0.8875162867420576}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:38:00,614] Trial 2 finished with value: 0.5515103340148926 and parameters: {'n_estimators': 669, 'max_depth': 10, 'learning_rate': 0.239203872610522, 'min_child_weight': 8, 'reg_lambda': 4.170991277434271, 'reg_alpha': 57.37989634834074, 'subsample': 0.5674525079848028, 'gamma': 8.73432878406298, 'colsample_bytree': 0.8268842770611133}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:38:11,260] Trial 3 finished with value: 0.5459356904029846 and parameters: {'n_estimators': 667, 'max_depth': 7, 'learning_rate': 0.2710937963465979, 'min_child_weight': 6, 'reg_lambda': 12.547045349462389, 'reg_alpha': 49.19479021044915, 'subsample': 0.5792883003421216, 'gamma': 7.543685579593041, 'colsample_bytree': 0.9081019129008399}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:38:25,492] Trial 4 finished with value: 0.5575486421585083 and parameters: {'n_estimators': 672, 'max_depth': 10, 'learning_rate': 0.23476392924647838, 'min_child_weight': 6, 'reg_lambda': 1.1065766447120509, 'reg_alpha': 52.45173167231298, 'subsample': 0.5127150205626432, 'gamma': 7.958327586431788, 'colsample_bytree': 0.8811503870285958}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:38:47,195] Trial 5 finished with value: 0.5464202165603638 and parameters: {'n_estimators': 747, 'max_depth': 10, 'learning_rate': 0.2440612718143217, 'min_child_weight': 8, 'reg_lambda': 1.0340365711720696, 'reg_alpha': 57.66113871762456, 'subsample': 0.5504398912811357, 'gamma': 7.821325148432163, 'colsample_bytree': 0.8157400465834516}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:38:55,309] Trial 6 finished with value: 0.542608380317688 and parameters: {'n_estimators': 643, 'max_depth': 7, 'learning_rate': 0.23822509487120863, 'min_child_weight': 6, 'reg_lambda': 1.5462681939966805, 'reg_alpha': 55.370114400629404, 'subsample': 0.5132678518931493, 'gamma': 7.803611064831868, 'colsample_bytree': 0.8461190302313212}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:39:08,102] Trial 7 finished with value: 0.558843195438385 and parameters: {'n_estimators': 717, 'max_depth': 10, 'learning_rate': 0.21249578846243775, 'min_child_weight': 5, 'reg_lambda': 1.8512436217165806, 'reg_alpha': 61.10740625383261, 'subsample': 0.7630154270981082, 'gamma': 8.48191177030447, 'colsample_bytree': 0.8278675928826748}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:39:19,873] Trial 8 finished with value: 0.5548970103263855 and parameters: {'n_estimators': 794, 'max_depth': 7, 'learning_rate': 0.2190998794890267, 'min_child_weight': 5, 'reg_lambda': 1.7171160272374444, 'reg_alpha': 45.96182260040386, 'subsample': 0.5215832015674355, 'gamma': 8.232146504037894, 'colsample_bytree': 0.8327993706044834}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:39:40,988] Trial 9 finished with value: 0.5479733347892761 and parameters: {'n_estimators': 616, 'max_depth': 10, 'learning_rate': 0.26409292519918776, 'min_child_weight': 8, 'reg_lambda': 1.8080416247127464, 'reg_alpha': 69.4652670622624, 'subsample': 0.5271930543938534, 'gamma': 8.894140965265123, 'colsample_bytree': 0.984787557550928}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:39:52,305] Trial 10 finished with value: 0.553533673286438 and parameters: {'n_estimators': 760, 'max_depth': 9, 'learning_rate': 0.2985369174788533, 'min_child_weight': 7, 'reg_lambda': 10.178143200033135, 'reg_alpha': 42.37137591420352, 'subsample': 0.6433855564206522, 'gamma': 7.1240434572278755, 'colsample_bytree': 0.9973616082431573}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:40:14,206] Trial 11 finished with value: 0.5541666746139526 and parameters: {'n_estimators': 730, 'max_depth': 9, 'learning_rate': 0.20512117296721577, 'min_child_weight': 5, 'reg_lambda': 2.699727779680175, 'reg_alpha': 64.5183180170933, 'subsample': 0.7982173325789914, 'gamma': 8.421826386381575, 'colsample_bytree': 0.94667967801947}. Best is trial 0 with value: 0.5615689158439636.
[I 2026-01-05 09:40:24,202] Trial 12 finished with value: 0.5653170347213745 and parameters: {'n_estimators': 721, 'max_depth': 9, 'learning_rate': 0.2868052184050213, 'min_child_weight': 5, 'reg_lambda': 2.7426034489764537, 'reg_alpha': 61.66804133271725, 'subsample': 0.7941785783855495, 'gamma': 7.013766422470301, 'colsample_bytree': 0.9324959967485495}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:40:33,643] Trial 13 finished with value: 0.5607832074165344 and parameters: {'n_estimators': 778, 'max_depth': 8, 'learning_rate': 0.291489336902975, 'min_child_weight': 5, 'reg_lambda': 5.567305473429673, 'reg_alpha': 41.67413375685687, 'subsample': 0.6826162757057209, 'gamma': 7.01005336885385, 'colsample_bytree': 0.9511733171710355}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:40:44,100] Trial 14 finished with value: 0.5650844573974609 and parameters: {'n_estimators': 699, 'max_depth': 9, 'learning_rate': 0.2748389974402879, 'min_child_weight': 6, 'reg_lambda': 2.854249368463152, 'reg_alpha': 63.34827721120128, 'subsample': 0.7058958862090746, 'gamma': 7.386481720484232, 'colsample_bytree': 0.9452387399590917}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:40:52,273] Trial 15 finished with value: 0.5552188754081726 and parameters: {'n_estimators': 696, 'max_depth': 8, 'learning_rate': 0.2593145208600781, 'min_child_weight': 7, 'reg_lambda': 6.622778801095844, 'reg_alpha': 65.95770424673728, 'subsample': 0.7277897226621612, 'gamma': 7.334053234640496, 'colsample_bytree': 0.9214170185307375}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:00,874] Trial 16 finished with value: 0.5584436655044556 and parameters: {'n_estimators': 750, 'max_depth': 8, 'learning_rate': 0.28600127242166196, 'min_child_weight': 6, 'reg_lambda': 3.2147967763783867, 'reg_alpha': 61.68953660139661, 'subsample': 0.7006833651140099, 'gamma': 7.576998570842407, 'colsample_bytree': 0.9434073831060148}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:11,435] Trial 17 finished with value: 0.5509581565856934 and parameters: {'n_estimators': 705, 'max_depth': 9, 'learning_rate': 0.28218876437856233, 'min_child_weight': 7, 'reg_lambda': 8.024189038181259, 'reg_alpha': 69.36942618566148, 'subsample': 0.6219808840688049, 'gamma': 7.200801811164792, 'colsample_bytree': 0.9244133631486637}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:20,108] Trial 18 finished with value: 0.5535688400268555 and parameters: {'n_estimators': 610, 'max_depth': 9, 'learning_rate': 0.25301592357598224, 'min_child_weight': 6, 'reg_lambda': 2.7180149783473664, 'reg_alpha': 61.76152538431768, 'subsample': 0.7526556438342371, 'gamma': 7.559935143527334, 'colsample_bytree': 0.8636424237239707}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:29,011] Trial 19 finished with value: 0.5569868087768555 and parameters: {'n_estimators': 650, 'max_depth': 8, 'learning_rate': 0.27775892728620644, 'min_child_weight': 7, 'reg_lambda': 3.197791411588593, 'reg_alpha': 66.3291038994003, 'subsample': 0.7937159495840949, 'gamma': 7.297916840925433, 'colsample_bytree': 0.963883310120175}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:37,154] Trial 20 finished with value: 0.5648521780967712 and parameters: {'n_estimators': 687, 'max_depth': 9, 'learning_rate': 0.2944546415529299, 'min_child_weight': 6, 'reg_lambda': 5.1959096518843, 'reg_alpha': 51.385148526055836, 'subsample': 0.6769460320186595, 'gamma': 7.0645725748935995, 'colsample_bytree': 0.9261851671769885}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:45,304] Trial 21 finished with value: 0.5586498975753784 and parameters: {'n_estimators': 686, 'max_depth': 9, 'learning_rate': 0.2993771814906818, 'min_child_weight': 6, 'reg_lambda': 17.453884759111446, 'reg_alpha': 50.32237108033679, 'subsample': 0.6803972685289456, 'gamma': 7.043645124975872, 'colsample_bytree': 0.9242904048393077}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:41:53,917] Trial 22 finished with value: 0.5585142970085144 and parameters: {'n_estimators': 712, 'max_depth': 9, 'learning_rate': 0.2888172694087301, 'min_child_weight': 5, 'reg_lambda': 5.119251401689987, 'reg_alpha': 58.72759696554614, 'subsample': 0.7204983262454112, 'gamma': 7.198739697354175, 'colsample_bytree': 0.9000106413136983}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:02,761] Trial 23 finished with value: 0.5584966540336609 and parameters: {'n_estimators': 733, 'max_depth': 9, 'learning_rate': 0.27280143438172716, 'min_child_weight': 6, 'reg_lambda': 3.3955400808068186, 'reg_alpha': 52.82586136534304, 'subsample': 0.6220311749299466, 'gamma': 7.455284476678135, 'colsample_bytree': 0.9377764574381777}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:10,709] Trial 24 finished with value: 0.5555663704872131 and parameters: {'n_estimators': 682, 'max_depth': 8, 'learning_rate': 0.26247886074662813, 'min_child_weight': 6, 'reg_lambda': 2.504368245274463, 'reg_alpha': 60.0291745938619, 'subsample': 0.6614470093004908, 'gamma': 7.032524806718163, 'colsample_bytree': 0.9665604942201653}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:19,477] Trial 25 finished with value: 0.5579981207847595 and parameters: {'n_estimators': 642, 'max_depth': 9, 'learning_rate': 0.29161388268462574, 'min_child_weight': 5, 'reg_lambda': 6.914518444488093, 'reg_alpha': 63.86522202358027, 'subsample': 0.758000967685185, 'gamma': 7.713761079002152, 'colsample_bytree': 0.919460467454304}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:27,268] Trial 26 finished with value: 0.5587402582168579 and parameters: {'n_estimators': 656, 'max_depth': 8, 'learning_rate': 0.280406393635761, 'min_child_weight': 6, 'reg_lambda': 4.158768673219457, 'reg_alpha': 47.58244076432902, 'subsample': 0.7240345271955312, 'gamma': 7.239897874907682, 'colsample_bytree': 0.8842426815004618}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:36,577] Trial 27 finished with value: 0.5567975640296936 and parameters: {'n_estimators': 695, 'max_depth': 9, 'learning_rate': 0.22837529829166675, 'min_child_weight': 5, 'reg_lambda': 5.303640871008622, 'reg_alpha': 53.2911494433519, 'subsample': 0.6013991031755956, 'gamma': 7.382436561050468, 'colsample_bytree': 0.9334925506371835}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:45,268] Trial 28 finished with value: 0.5637944340705872 and parameters: {'n_estimators': 627, 'max_depth': 10, 'learning_rate': 0.29938561187393575, 'min_child_weight': 7, 'reg_lambda': 1.2729878438945963, 'reg_alpha': 63.659239822408296, 'subsample': 0.775838681179327, 'gamma': 7.137726483180491, 'colsample_bytree': 0.9562315781495987}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:42:54,313] Trial 29 finished with value: 0.5611048936843872 and parameters: {'n_estimators': 723, 'max_depth': 9, 'learning_rate': 0.2697385429157444, 'min_child_weight': 5, 'reg_lambda': 2.113961520002456, 'reg_alpha': 67.44265105745053, 'subsample': 0.7029758438739833, 'gamma': 7.431925350499408, 'colsample_bytree': 0.9814132329238886}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:43:02,707] Trial 30 finished with value: 0.5643876791000366 and parameters: {'n_estimators': 735, 'max_depth': 9, 'learning_rate': 0.2552704721565767, 'min_child_weight': 6, 'reg_lambda': 2.3172249892845587, 'reg_alpha': 51.02625385520638, 'subsample': 0.6530973831922332, 'gamma': 7.652133167533377, 'colsample_bytree': 0.9139969368992876}. Best is trial 12 with value: 0.5653170347213745.
[I 2026-01-05 09:43:11,465] Trial 31 finished with value: 0.5670492649078369 and parameters: {'n_estimators': 738, 'max_depth': 9, 'learning_rate': 0.2550646179553546, 'min_child_weight': 6, 'reg_lambda': 2.1578498368921903, 'reg_alpha': 48.85391597417524, 'subsample': 0.6552829800977559, 'gamma': 7.669754402232104, 'colsample_bytree': 0.9080998712715589}. Best is trial 31 with value: 0.5670492649078369.
[I 2026-01-05 09:43:21,921] Trial 32 finished with value: 0.5630756616592407 and parameters: {'n_estimators': 765, 'max_depth': 9, 'learning_rate': 0.2765883810099078, 'min_child_weight': 6, 'reg_lambda': 3.666717968088486, 'reg_alpha': 43.79193976633063, 'subsample': 0.6747621958390712, 'gamma': 7.946807660861917, 'colsample_bytree': 0.9010188544856619}. Best is trial 31 with value: 0.5670492649078369.
[I 2026-01-05 09:43:34,429] Trial 33 finished with value: 0.5609628558158875 and parameters: {'n_estimators': 705, 'max_depth': 9, 'learning_rate': 0.267753169997654, 'min_child_weight': 7, 'reg_lambda': 1.39390112369039, 'reg_alpha': 55.591059608883874, 'subsample': 0.6352861014093235, 'gamma': 7.354982584656247, 'colsample_bytree': 0.8699990750100104}. Best is trial 31 with value: 0.5670492649078369.
[I 2026-01-05 09:43:51,079] Trial 34 finished with value: 0.5652939081192017 and parameters: {'n_estimators': 742, 'max_depth': 10, 'learning_rate': 0.284068376709451, 'min_child_weight': 5, 'reg_lambda': 2.8962810152319056, 'reg_alpha': 47.91500178659679, 'subsample': 0.7357505843503271, 'gamma': 7.499920715657048, 'colsample_bytree': 0.9346680998794406}. Best is trial 31 with value: 0.5670492649078369.
[I 2026-01-05 09:44:00,993] Trial 35 finished with value: 0.5700187683105469 and parameters: {'n_estimators': 744, 'max_depth': 10, 'learning_rate': 0.2530323735961582, 'min_child_weight': 5, 'reg_lambda': 2.088093762053857, 'reg_alpha': 47.83976609847647, 'subsample': 0.7453445081837838, 'gamma': 8.162020976538475, 'colsample_bytree': 0.9069274697019746}. Best is trial 35 with value: 0.5700187683105469.
[I 2026-01-05 09:44:11,757] Trial 36 finished with value: 0.5694334506988525 and parameters: {'n_estimators': 743, 'max_depth': 10, 'learning_rate': 0.24767845632171162, 'min_child_weight': 5, 'reg_lambda': 2.227352926410788, 'reg_alpha': 48.09594871185297, 'subsample': 0.741673554380875, 'gamma': 8.230430772157334, 'colsample_bytree': 0.9052778137757618}. Best is trial 35 with value: 0.5700187683105469.
[I 2026-01-05 09:44:27,444] Trial 37 finished with value: 0.5631970167160034 and parameters: {'n_estimators': 762, 'max_depth': 10, 'learning_rate': 0.24756683593855516, 'min_child_weight': 9, 'reg_lambda': 2.2802241911351415, 'reg_alpha': 45.54451898124891, 'subsample': 0.7760926472799317, 'gamma': 8.201874745823902, 'colsample_bytree': 0.8943375998765596}. Best is trial 35 with value: 0.5700187683105469.
[I 2026-01-05 09:44:38,458] Trial 38 finished with value: 0.5680278539657593 and parameters: {'n_estimators': 778, 'max_depth': 10, 'learning_rate': 0.22966228907081976, 'min_child_weight': 5, 'reg_lambda': 1.999887266014725, 'reg_alpha': 47.870137981149206, 'subsample': 0.7404399400119146, 'gamma': 8.132538919166722, 'colsample_bytree': 0.9082732935337486}. Best is trial 35 with value: 0.5700187683105469.
[I 2026-01-05 09:44:57,636] Trial 39 finished with value: 0.5682632923126221 and parameters: {'n_estimators': 799, 'max_depth': 10, 'learning_rate': 0.2304702439961982, 'min_child_weight': 5, 'reg_lambda': 1.240988796394373, 'reg_alpha': 48.57799180112925, 'subsample': 0.7500518952280386, 'gamma': 8.10563146081624, 'colsample_bytree': 0.8711890256642996}. Best is trial 35 with value: 0.5700187683105469.
[I 2026-01-05 09:45:08,081] Trial 40 finished with value: 0.5707206130027771 and parameters: {'n_estimators': 797, 'max_depth': 10, 'learning_rate': 0.22818765885136288, 'min_child_weight': 5, 'reg_lambda': 1.1487514578072058, 'reg_alpha': 46.854867089592425, 'subsample': 0.742345953380381, 'gamma': 8.15986014697061, 'colsample_bytree': 0.8733568871807899}. Best is trial 40 with value: 0.5707206130027771.
[I 2026-01-05 09:45:19,347] Trial 41 finished with value: 0.5640112161636353 and parameters: {'n_estimators': 799, 'max_depth': 10, 'learning_rate': 0.2296911516874481, 'min_child_weight': 5, 'reg_lambda': 1.1460344951223538, 'reg_alpha': 46.724749794078996, 'subsample': 0.7423582088945048, 'gamma': 8.147483047064567, 'colsample_bytree': 0.8731284370887855}. Best is trial 40 with value: 0.5707206130027771.
[I 2026-01-05 09:45:29,269] Trial 42 finished with value: 0.5703155398368835 and parameters: {'n_estimators': 785, 'max_depth': 10, 'learning_rate': 0.2221249855375838, 'min_child_weight': 5, 'reg_lambda': 1.529980809820603, 'reg_alpha': 43.448650864502994, 'subsample': 0.7728007817278668, 'gamma': 8.388566875095343, 'colsample_bytree': 0.8587266848875083}. Best is trial 40 with value: 0.5707206130027771.
[I 2026-01-05 09:45:38,794] Trial 43 finished with value: 0.5717765092849731 and parameters: {'n_estimators': 787, 'max_depth': 10, 'learning_rate': 0.219303313082108, 'min_child_weight': 5, 'reg_lambda': 1.5679967253646943, 'reg_alpha': 44.0354094949432, 'subsample': 0.7745298900112605, 'gamma': 8.389677553813932, 'colsample_bytree': 0.8528897500737364}. Best is trial 43 with value: 0.5717765092849731.
[I 2026-01-05 09:45:48,187] Trial 44 finished with value: 0.5708529353141785 and parameters: {'n_estimators': 784, 'max_depth': 10, 'learning_rate': 0.22114957678521588, 'min_child_weight': 5, 'reg_lambda': 1.5750345997785111, 'reg_alpha': 43.95419256301597, 'subsample': 0.7735906319535457, 'gamma': 8.38061420427708, 'colsample_bytree': 0.8490280575362699}. Best is trial 43 with value: 0.5717765092849731.
[I 2026-01-05 09:45:57,418] Trial 45 finished with value: 0.566116452217102 and parameters: {'n_estimators': 785, 'max_depth': 10, 'learning_rate': 0.21656982343668588, 'min_child_weight': 8, 'reg_lambda': 1.5749621547500472, 'reg_alpha': 40.48467886295621, 'subsample': 0.7703784640240461, 'gamma': 8.450076263110326, 'colsample_bytree': 0.8503998418550396}. Best is trial 43 with value: 0.5717765092849731.
[I 2026-01-05 09:46:10,170] Trial 46 finished with value: 0.5671770572662354 and parameters: {'n_estimators': 787, 'max_depth': 10, 'learning_rate': 0.22419288929949663, 'min_child_weight': 5, 'reg_lambda': 1.005471288413615, 'reg_alpha': 43.67735827203059, 'subsample': 0.7830151884606154, 'gamma': 8.557417523482469, 'colsample_bytree': 0.80380633067203}. Best is trial 43 with value: 0.5717765092849731.
[I 2026-01-05 09:46:19,273] Trial 47 finished with value: 0.5716687440872192 and parameters: {'n_estimators': 774, 'max_depth': 10, 'learning_rate': 0.20655767129422214, 'min_child_weight': 5, 'reg_lambda': 1.4850785021275916, 'reg_alpha': 44.20063403362206, 'subsample': 0.764766415144338, 'gamma': 8.32026394458276, 'colsample_bytree': 0.8464444057848265}. Best is trial 43 with value: 0.5717765092849731.

{'n_estimators': 787,
 'max_depth': 10,
 'learning_rate': 0.219303313082108,
 'min_child_weight': 5,
 'reg_lambda': 1.5679967253646943,
 'reg_alpha': 44.0354094949432,
 'subsample': 0.7745298900112605,
 'gamma': 8.389677553813932,
 'colsample_bytree': 0.8528897500737364}

In [10]:
final_model = XGBRegressor(**best_params, device='gpu', verbosity=1, random_state=42)

pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', final_model)
    ]
)

pipeline.fit(X_train, y_train)

pred = pipeline.predict(X_test)

print(f'R2 {r2_score(y_test, pred)}')
print(f'MSE {mean_squared_error(y_test, pred)}')
print(f'RMSE {math.sqrt(mean_squared_error(y_test, pred))}')
print(f'MAE {mean_absolute_error(y_test, pred)}')

R2 0.5717765092849731
MSE 53.45294189453125
RMSE 7.311151885614964
MAE 5.547699451446533